#!/bin/sh

# Capture original working directory BEFORE changing to arsenal dir
export ARSENAL_LAUNCH_DIR="$PWD"

if [ -L $0 ] ; then
    DIR=$(dirname "$(readlink -f "$0")") ;
else
    DIR=$(dirname "$0") ;
fi ;

cd "$DIR"

export TERM='xterm-256color'
exec python3 -m arsenal "$@"
